name: userverse_dart_client
description: A Dart client for integrating with the Userverse platform.
version: 0.0.1

homepage: https://github.com/SoftwareVerse
repository: https://github.com/SoftwareVerse/userverse-dart-client
issue_tracker: https://github.com/SoftwareVerse/userverse-dart-client/issues

environment:
  sdk: ">=3.2.0 <4.0.0"

topics:
  - user-management
  - rbac
  - multi-tenancy
  - client

dependencies:
  http: ^1.4.0

dev_dependencies:
  lints: ^6.0.0
  mockito: ^5.4.4
  test: ^1.24.0
  build_runner: ^2.4.0
